// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240927235014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app.Models.Diagram1.Cliente", b =>
                {
                    b.Property<long?>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<float?>("Credito")
                        .HasColumnType("real");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.HasKey("PersonaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("app.Models.Diagram1.Empresa", b =>
                {
                    b.Property<long?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Codigo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("app.Models.Diagram1.Factura", b =>
                {
                    b.Property<long?>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Numero"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Numero");

                    b.HasIndex("ClienteId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("app.Models.Diagram1.Persona", b =>
                {
                    b.Property<long?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Codigo"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonaCodigo")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonaReferenciaCodigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("PersonaReferenciaCodigo");

                    b.ToTable("Persona");

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("app.Models.Diagram1.Producto", b =>
                {
                    b.Property<long?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Codigo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("app.Models.Diagram1.ProductosPorFactura", b =>
                {
                    b.Property<long?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Codigo"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<long>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<double>("Subtotal")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosPorFactura");
                });

            modelBuilder.Entity("app.Models.Diagram1.Vendedor", b =>
                {
                    b.HasBaseType("app.Models.Diagram1.Persona");

                    b.Property<int>("Carnet")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PersonaCodigo");

                    b.HasDiscriminator().HasValue("Vendedor");
                });

            modelBuilder.Entity("app.Models.Diagram1.Cliente", b =>
                {
                    b.HasOne("app.Models.Diagram1.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Diagram1.Persona", "Persona")
                        .WithMany("Clientes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("app.Models.Diagram1.Factura", b =>
                {
                    b.HasOne("app.Models.Diagram1.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("app.Models.Diagram1.Persona", b =>
                {
                    b.HasOne("app.Models.Diagram1.Persona", "PersonaReferencia")
                        .WithMany()
                        .HasForeignKey("PersonaReferenciaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaReferencia");
                });

            modelBuilder.Entity("app.Models.Diagram1.ProductosPorFactura", b =>
                {
                    b.HasOne("app.Models.Diagram1.Factura", "Factura")
                        .WithMany("ProductosPorFactura")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Diagram1.Producto", "Producto")
                        .WithMany("ProductosPorFactura")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("app.Models.Diagram1.Vendedor", b =>
                {
                    b.HasOne("app.Models.Diagram1.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaCodigo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("app.Models.Diagram1.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("app.Models.Diagram1.Empresa", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("app.Models.Diagram1.Factura", b =>
                {
                    b.Navigation("ProductosPorFactura");
                });

            modelBuilder.Entity("app.Models.Diagram1.Persona", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("app.Models.Diagram1.Producto", b =>
                {
                    b.Navigation("ProductosPorFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
